// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeSet } from "./ChangeSet";
import type { ChangeSetHunkResult } from "./ChangeSetHunkResult";

/**
 * Publishes changed file/hunk decisions and their aggregate state together.
 * Full snapshots allow subscribers to update without re-diffing or polling.
 */
export type ChangeSetUpdatedNotification = { changeSet: ChangeSet, results: Array<ChangeSetHunkResult>, };
