// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read session-local review data after turn completion or interruption.
 */
export type ChangeSetReadParams = { threadId: string, turnId: string, };
