// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accept/revert one Pending hunk. No client-supplied paths or patches execute.
 */
export type ChangeSetHunkReviewParams = { threadId: string, turnId: string, changeSetId: string, fileId: string, hunkId: string, };
