// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeReviewState } from "./ChangeReviewState";
import type { ChangeSetFile } from "./ChangeSetFile";

/**
 * One finalized logical change set per turn. Review does not regenerate IDs.
 */
export type ChangeSet = { id: string,
/**
 * Monotonic decision revision; clients can discard delayed notifications.
 */
revision: number, threadId: string, turnId: string, state: ChangeReviewState,
/**
 * MVP coverage is `applyPatchOnly`: arbitrary shell/MCP writes are not tracked.
 */
coverage: string,
/**
 * Storage is `sessionMemory`: restart/unload loses review data.
 */
storage: string, files: Array<ChangeSetFile>, };
