// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeSet } from "./ChangeSet";

/**
 * Published once after a tracked turn finishes or is interrupted.
 */
export type ChangeSetCreatedNotification = { changeSet: ChangeSet, };
