// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Text file presence relative to its first mutation in the turn.
 */
export type ChangeSetFileKind = "added" | "modified" | "deleted";
