// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HunkLocationResult } from "./HunkLocationResult";

/**
 * Path uses the same absolute executor path URI as ChangeSetFile.path.
 */
export type ChangeSetHunkLocateResponse = { changeSetId: string, fileId: string, hunkId: string, path: string, result: HunkLocationResult, };
