// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeSet } from "./ChangeSet";
import type { ChangeSetHunkResult } from "./ChangeSetHunkResult";

/**
 * Complete snapshot and individual outcomes, including partial success.
 * A rollback conflict is a normal result, not a JSON-RPC failure. Invalid IDs
 * and attempts to review a running thread are JSON-RPC errors.
 */
export type ChangeSetReviewResponse = { changeSet: ChangeSet, results: Array<ChangeSetHunkResult>, };
