// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accept/revert Pending hunks in one file, preserving Accepted and Conflict.
 */
export type ChangeSetFileReviewParams = { threadId: string, turnId: string, changeSetId: string, fileId: string, };
