// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate review state. Mixed terminal decisions are `Reviewed`.
 */
export type ChangeReviewState = "pending" | "accepted" | "reverted" | "conflict" | "reviewed" | "unsupported";
