// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeSet } from "./ChangeSet";

/**
 * Null means no finalized ChangeSet is retained (live turn, unloaded session,
 * restarted process, or a task that did not use the patch tracker).
 */
export type ChangeSetReadResponse = { changeSet: ChangeSet | null, };
