// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List finalized review snapshots retained by this loaded session, independently
 * of conversation history mode. This does not read persisted ChangeSets.
 */
export type ChangeSetListParams = { threadId: string, };
