// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeHunk } from "./ChangeHunk";
import type { ChangeReviewState } from "./ChangeReviewState";
import type { ChangeSetFileKind } from "./ChangeSetFileKind";

/**
 * A file's first baseline and last exact Codex result, never Git HEAD.
 */
export type ChangeSetFile = { id: string, environmentId: string,
/**
 * Absolute path URI, consistent with executor environment addressing.
 */
path: string, changeType: ChangeSetFileKind, beforeHash: string | null, afterHash: string | null,
/**
 * UTF-8 content for native IDE diffs. Null means absent or unsupported.
 */
beforeContent: string | null, afterContent: string | null, state: ChangeReviewState, hunks: Array<ChangeHunk>,
/**
 * Unsupported files are visible but cannot be accepted or reverted.
 */
unsupportedReason: string | null, };
