// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query live filesystem coordinates without changing review state or emitting
 * notifications. Historical oldStart/newStart remain unchanged.
 */
export type ChangeSetHunkLocateParams = { threadId: string, turnId: string, changeSetId: string, fileId: string, hunkId: string, };
