// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeReviewState } from "./ChangeReviewState";

/**
 * An immutable diff identity with a mutable review decision.
 */
export type ChangeHunk = { id: string,
/**
 * Historical baseline -> turn-final unified diff coordinates, never live
 * filesystem positions. Nonempty starts are one-based; empty ranges use
 * the preceding line number (zero at BOF). Use hunk/locate for navigation.
 */
oldStart: number, oldLines: number,
/**
 * Historical turn-final coordinate, with the same unified diff convention.
 */
newStart: number, newLines: number,
/**
 * Unified diff hunk, preserving line endings and missing-final-newline markers.
 */
patch: string, state: ChangeReviewState,
/**
 * Why rollback was refused; no forced rollback is available.
 */
conflict: string | null, };
