// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeReviewState } from "./ChangeReviewState";

/**
 * Per-hunk outcome, including unchanged accepted/reverted/conflicted hunks in bulk calls.
 */
export type ChangeSetHunkResult = { fileId: string, hunkId: string, state: ChangeReviewState, changed: boolean, message: string | null, };
