// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a live range should be revealed in the current file.
 */
export type CurrentHunkRangeKind = "content" | "deletionAnchor" | "filePresence";
