// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentHunkRangeKind } from "./CurrentHunkRangeKind";
import type { HunkNotPresentReason } from "./HunkNotPresentReason";

/**
 * Read-only, point-in-time location; never changes review decisions.
 */
export type HunkLocationResult = { "status": "located",
/**
 * One-based current line (consistent with protocol file locations).
 * For an anchor, the insertion point before this line; EOF is N + 1.
 */
startLine: number,
/**
 * Current after-side lines, excluding matching context. Zero for anchors.
 */
lineCount: number, kind: CurrentHunkRangeKind, } | { "status": "notPresent", reason: HunkNotPresentReason, } | { "status": "conflict", reason: string, } | { "status": "unsupported", reason: string, };
